name: CI
# This workflow is triggered on pull request to the repository.
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter pub get
      - run: flutter build apk
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
